name: youthread

on:
    workflow_dispatch:
    schedule:
      - cron: "0 */2 * * *"
    watch:
      types: [started]
    repository_dispatch:
      types: youthread

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: npm install
        run: |
          npm install
      - name: '运行 【中青自动阅读】'
        run: |
          node Task/youthread.js
        env:
          YOUTH_READ: ${{ secrets.YOUTH_READ }}
          PUSH_KEY: ${{ secrets.PUSH_KEY }}
          BARK_PUSH: ${{ secrets.BARK_PUSH }}
          BARK_SOUND: ${{ secrets.BARK_SOUND }}
          TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
          TG_USER_ID: ${{ secrets.TG_USER_ID }}
