name: crazyjoin_coins

on:
    workflow_dispatch:
    schedule:
      - cron: "10 7 * * *"
    watch:
      types: [started]
    repository_dispatch:
      types: jd_crazy_joy_coin.js

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: npm install
        run: |
          npm install
      - name: '运行 【crazyjoy挂机】'
        run: |
          node Task/jd_crazy_joy_coin.js.js
        env:
          JD_COOKIE: ${{ secrets.JD_COOKIE }}
          PUSH_KEY: ${{ secrets.PUSH_KEY }}
          BARK_PUSH: ${{ secrets.BARK_PUSH }}
          BARK_SOUND: ${{ secrets.BARK_SOUND }}
          TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
          TG_USER_ID: ${{ secrets.TG_USER_ID }}
