name: ymzhuan

on:
    workflow_dispatch:
    schedule:
      - cron: "0 8,12 * * *"
    watch:
      types: [started]
    repository_dispatch:
      types: ymzhuan

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: npm install
        run: |
          npm install
      - name: '运行 【羊毛赚】'
        run: |
          node Task/ymzhuan.js
        env:
          YMZ_ymzhuanggBODY: ${{ secrets.YMZ_ymzhuanggBODY }}
          YMZ_ymzhuanspBODY: ${{ secrets.YMZ_ymzhuanspBODY }}
          YMZ_ymzhuantxBODY: ${{ secrets.YMZ_ymzhuantxBODY }}
          YMZ_CASH: ${{ secrets.YMZ_CASH }}
          BARK_SOUND: ${{ secrets.BARK_SOUND }}
          TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
          TG_USER_ID: ${{ secrets.TG_USER_ID }}
