# ziye
# github地址  https://github.com/6Svip120apk69
# TG频道地址  https://t.me/ziyescript
# TG交流群    https://t.me/joinchat/thormuxinAAE7XHm-q1-7Np-tF3g
# boxjs链接   https://raw.githubusercontent.com/6Svip120apk69/gitee_q8qsTAUA_cThxc1RBVUE/main/Task/ziye.boxjs.json



# ⚠️⚠️⚠️特别重要,务必进行替换操作，不得使用原作者地址

# 具体方法请看: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions



#  以账号    thormuxin
#  仓库地址  https://github.com/thormuxin/jave 
#  文件地址   https://raw.githubusercontent.com/thormuxin/jave/ZIYE/Task/zhima.js    为例 


# 主要替换的字符👇

# zhima     //js名字
# 0 0-15   //定时，如北京时间8到23点，设置0-15
# ZM_zhimabody   //环境变量之一，47行处自行添加其他
# thormuxin      //账号名
# jave      //仓库名
# ZIYE     //分支名
# Task/zhima.js  //子文件地址




name: zhima

on:
  workflow_dispatch:
  schedule:
     - cron: '0 * * * *'
  watch:
    types: started
jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    env:
        ZM_zhimabody: ${{ secrets.ZM_zhimabody }}
        XL_HEADER: ${{ secrets.XL_HEADER }}		
        
    steps:
      - name: Checkout
        run: |
          git clone https://github.com/thormuxin/jave.git ~/jave
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: npm install
        if: env.ZM_zhimabody
        run: |
          cd ~/jave
          git checkout ZIYE
          npm install
      - name: '运行 【zhima】'
        if: env.ZM_zhimabody
        run: |
          cd ~/jave
          node Task/zhima.js
        env:
          ZM_zhimatxbody: ${{ secrets.ZM_zhimatxbody }} 
          ZM_CASH: ${{ secrets.ZM_CASH }}          
          PUSH_KEY: ${{ secrets.PUSH_KEY }}
          BARK_PUSH: ${{ secrets.BARK_PUSH }}
          TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
          TG_USER_ID: ${{ secrets.TG_USER_ID }}
          BARK_SOUND: ${{ secrets.BARK_SOUND }}
          DD_BOT_TOKEN: ${{ secrets.DD_BOT_TOKEN }}
          DD_BOT_SECRET: ${{ secrets.DD_BOT_SECRET }}
